server:
  port: 80

spring:
  application:
    name: cloud-consumer-feign-hystrix-order80


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

feign:
  circuitbreaker:
    enabled: true
config:
    info: http://eureka3355.com:3355/eureka
